---
title: "Bivariate Viz"
---

Use this file to generate a professional looking **bivariate** visualization.  The visualization will not perfect the first time but you are expected to improve it throughout the semester especially after covering advanced topics such as effective viz.
```{r}

# Load required libraries
library(clipr)
library(cpp11)
library(crayon)
library(data.table)
library(dbplyr)
library(dplyr)
library(dtplyr)
library(fivethirtyeight)
library(fivethirtyeightdata)
library(ggformula)
library(gtools)
library(hexbin)
library(labelled)
library(labeling)
library(leaflet)
library(leaflet.providers)
library(magrittr)
library(lubridate)
library(maps)
library(mosaic)
library(mosaicCore)
library(viridis)
library(tidyselect)
library(tidyr)
library(tidyverse)
```

#The Political Trends of America

::: {.callout-note title="This bivariate publication shows the distribution of republican voters across state lines in the form of percantages of the greater population as it pertains to the 2020 elections"}

PLACE YOUR SUMMARY IN THIS CALLOUT BOX

```{r}
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")
```

```{r}
#| fig-alt: "A graph that shows three faceted plots of the density of historical voting patterns in blue, purple and red states as it pertains to the distribution of republican voters in 2020"

ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density(alpha = 0.6) +
  scale_fill_manual(values = c("blue", "purple", "red")) +
  facet_wrap(~ historical)+
  theme(legend.position = "top",
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5),strip.text = element_text(size = 12, face = "bold"), 
    plot.subtitle = element_text(face = "bold", size = 10, hjust = 0.5)) + 
  labs(title = "Distribution of Republican Voter % (2020)",
    subtitle = "Density plots segmented by historical voting patterns",
    x = "% of Republican Voters",
    y = "Density",
    fill = "Historical Voting Pattern")
```
```



