---
title: "Univariate Viz"
---

This is a univariate visualisation for news publications across the United States provided by Kaggle. 

```{r}
news_orgs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2022/2022-04-05/news_orgs.csv')
```
```{r}
# Load required libraries
library(clipr)
library(cpp11)
library(crayon)
library(data.table)
library(dbplyr)
library(dplyr)
library(dtplyr)
library(fivethirtyeight)
library(ggplot2)
library(fivethirtyeightdata)
library(ggformula)
library(gtools)
library(hexbin)
library(labelled)
library(labeling)
library(leaflet)
library(leaflet.providers)
library(magrittr)
library(lubridate)
library(maps)
library(mosaic)
library(mosaicCore)
library(viridis)
library(tidyselect)
library(tidyr)
library(tidyverse)

```


::: {.callout-note title="A Note about the Biggest News Publications in America"}

 This univariate visualisation is aimed at showcasing the cities with the biggest American news publications, practice some basic data exploration and data viz in guided settings.

:::

```{r}
library(ggplot2)
#| fig-alt: "A graph that lists the major cities that have more than five news organisations and plots a barchart displaying colors for each city, with a range from 15+ in new york to 6 in charlotte"

news_orgs |> filter(!is.na(city)) |> count(city) |> filter(n > 5) |>              
  ggplot(aes(x = city, y = n, fill = city)) +   
  geom_bar(stat = "identity") +    
  theme_minimal() +
  theme(legend.position = "top", plot.title = element_text(face = "bold", size = 16, hjust = 0.5),strip.text = element_text(size = 12, face = "bold"), 
    plot.subtitle = element_text(face = "bold", size = 10, hjust = 0.5)) +
  labs(x = "Major Cities", y = "News Org Count", title = "Cities with 5+ News Orgs", subtitle = "By David Manguluti 2025, TidyTuesday")
```

